# Change the port to 8082 to guarantee there are no port conflicts
server.port=${PORT:8082}

# Turn off the database connection requirement for now (since you have Data JPA installed)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${H2_USERNAME}
spring.datasource.password=${H2_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Completely disable Spring Security's default login lockouts while developing
spring.security.user.name=${SPRING_SEC_USER}
spring.security.user.password=${SPRING_SEC_PWD}